backend:
  name: github
  repo: heinerbehrends/gatsby-portfolio
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - label: Book
    name: books
    folder: src/content
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Meta, name: meta, widget: object, required: false, fields: 
        - {
            label: Open Graph description,
            name: ogDescription,
            widget: text,
            pattern: [".{12, 110}", "Must be between 12 and 115 characters long."],
          }
        - {
            label: Open Graph image,
            name: ogImage,
            widget: image,
        }
        }
      
      - label: Image
        name: image
        widget: object
        fields:
          - { label: Image, name: src, widget: image }
          - { label: Alt, name: alt, widget: string }
