backend:
  name: github
  repo: heinerbehrends/gatsby-portfolio
  branch: main

media_folder: src/images
public_folder: /images

collections:
  - label: Books
    name: books
    folder: src/content
    extension: json
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - label: Image
        name: image
        widget: object
        fields:
          - { label: Image, name: src, widget: image }
          - { label: Alt, name: alt, widget: string }
