backend:
  name: github
  repo: heinerbehrends/gatsby-portfolio
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - label: Book
    name: books
    folder: src/content/books
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - label: Image
        name: image
        widget: object
        fields:
          - { label: Image, name: src, widget: image }
          - { label: Alt, name: alt, widget: string }
      - label: Meta
        name: meta
        widget: object
        required: false
        fields:
          - {
              label: Open Graph Description,
              name: ogDescription,
              widget: text,
              pattern:
                [".{12,115}", "Must be between 12 and 115 characters long"],
              hint: Maximale lengte is 115 tekens.,
              required: false,
            }
          - {
              label: Open Graph Image,
              name: ogImage,
              widget: image,
              hint: Gebruik een foto met een ratio van 1.91:1 en een minimale afmeting van 1200 x 630,
              required: false,
            }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Info"
        name: "info"
        file: "src/content/info/info-page.yml"
        fields:
          - { label: About, name: about, widget: list, allow_add: true }
          - label: Adress
            name: address
            widget: object
            required: true
            fields:
              - { label: email, name: email, widget: string }
              - { label: phone, name: phone, widget: string }
              - { label: insta, name: insta, widget: string }
              - { label: website, name: website, widget: string }
